let livros = [
    {
    "id":1,
    "Titulo": "As fadas do bosque encantado",
    "Autor": "Rodrigo Gazza",
    "Edição": "7",
    "Ano de lancamento": 2005,
    "Editora": "Arco-iris",
    "Local de publicacao": "Sao Paulo",
    "Classificacao": "Livre",
    "Codigo": "4321",
    "Assunto": "Fantasia",
    },
    {
    "id":2,
    "Titulo": "Morte a morte de Quincas Berro D'agua",
    "Autor": "Amado Batista",
    "Edição": "10",
    "Ano de lancamento": 1998,
    "Editora": "Livre Cultura",
    "Local de publicacao": "Rio de Janeiro",
    "Classificacao": "12 anos",
    "Codigo": "ff-01",
    "Assunto": "Contos",
    },
    {
    "id":3,
    "Titulo": "Te amar foi um erro",
    "Autor": "Jorge Amado",
    "Edição": "23",
    "Ano de lancamento": 1987,
    "Editora": "Curitiba",
    "Local de publicacao": "Paraná",
    "Classificacao": "16 anos",
    "Codigo": "rdx32",
    "Assunto": "Romance",
    },
    {
    "id":4,
    "Titulo": "A noiva cadaver",
    "Autor": "Albert Francis Lopez",
    "Edição": "54",
    "Ano de lancamento": 2001,
    "Editora": "Chick Chick",
    "Local de publicacao": "London",
    "Classificacao": "16 anos",
    "Codigo": "LD9833u",
    "Assunto": "Romance",
    },
    {
    "id":5,
    "Titulo": "Chapeuzinho cor de Rosa",
    "Autor": "Petrunfo Albinar Fontes",
    "Edição": "46",
    "Ano de lancamento": 2001,
    "Editora": "Le Livros",
    "Local de publicacao": "Minas Gerais",
    "Classificacao": "Livre",
    "Codigo": "ijn09",
    "Assunto": "Fantasia",
}]